/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdlRecord {
  'activityType' : string,
  'assistanceLevel' : string,
  'notes' : string,
  'timestamp' : bigint,
  'supervisorId' : Principal,
}
export interface MarRecord {
  'medicationName' : string,
  'dosage' : string,
  'nurseId' : Principal,
  'timestamp' : bigint,
  'administrationTime' : string,
}
export type ResidentId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VitalsRecord {
  'temperature' : number,
  'bloodPressure' : string,
  'timestamp' : bigint,
  'pulse' : bigint,
  'bloodOxygen' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdlRecord' : ActorMethod<[ResidentId, AdlRecord], undefined>,
  'createMarRecord' : ActorMethod<[ResidentId, MarRecord], undefined>,
  'createResidentProfile' : ActorMethod<[ResidentId], undefined>,
  'createVitalsEntry' : ActorMethod<[ResidentId, VitalsRecord], undefined>,
  'deleteAdlRecord' : ActorMethod<[ResidentId, bigint], undefined>,
  'deleteMarRecord' : ActorMethod<[ResidentId, bigint], undefined>,
  'deleteVitalsEntry' : ActorMethod<[ResidentId, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAdlRecords' : ActorMethod<[ResidentId], Array<AdlRecord>>,
  'listMarRecords' : ActorMethod<[ResidentId], Array<MarRecord>>,
  'listVitalsEntries' : ActorMethod<[ResidentId], Array<VitalsRecord>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];