/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdlRecord {
  'activityType' : string,
  'assistanceLevel' : string,
  'notes' : string,
  'timestamp' : bigint,
  'supervisorId' : Principal,
}
export interface DirectoryLoadPerformance {
  'backendQueryTimeNanos' : bigint,
  'totalRequestTimeNanos' : bigint,
  'residentCount' : bigint,
}
export interface HealthCheckResponse {
  'status' : string,
  'message' : string,
  'timestamp' : bigint,
  'canisterId' : string,
}
export interface InsuranceInfo {
  'company' : string,
  'address' : string,
  'contactNumber' : string,
  'policyNumber' : string,
}
export interface MarRecord {
  'medicationName' : string,
  'dosage' : string,
  'nurseId' : Principal,
  'timestamp' : bigint,
  'administrationTime' : string,
}
export interface Medication {
  'medicationName' : string,
  'dosage' : string,
  'prescribingPhysician' : string,
  'administrationTimes' : Array<string>,
}
export interface PharmacyInfo {
  'name' : string,
  'address' : string,
  'contactNumber' : string,
}
export interface Physician {
  'name' : string,
  'specialty' : string,
  'contactNumber' : string,
}
export interface Resident {
  'id' : ResidentId,
  'bed' : [] | [string],
  'active' : boolean,
  'birthDate' : string,
  'owner' : Principal,
  'admissionDate' : string,
  'name' : string,
  'createdAt' : bigint,
  'roomNumber' : string,
  'insurance' : InsuranceInfo,
  'medications' : Array<Medication>,
  'pharmacy' : PharmacyInfo,
  'responsiblePersons' : Array<ResponsiblePerson>,
  'medicaidNumber' : string,
  'physicians' : Array<Physician>,
  'roomType' : string,
  'medicareNumber' : string,
}
export interface ResidentCreateRequest {
  'id' : ResidentId,
  'bed' : [] | [string],
  'birthDate' : string,
  'admissionDate' : string,
  'name' : string,
  'roomNumber' : string,
  'insurance' : InsuranceInfo,
  'medications' : Array<Medication>,
  'pharmacy' : PharmacyInfo,
  'responsiblePersons' : Array<ResponsiblePerson>,
  'medicaidNumber' : string,
  'physicians' : Array<Physician>,
  'roomType' : string,
  'medicareNumber' : string,
}
export interface ResidentDirectoryEntry {
  'id' : ResidentId,
  'bed' : [] | [string],
  'active' : boolean,
  'birthDate' : string,
  'admissionDate' : string,
  'name' : string,
  'createdAt' : bigint,
  'roomNumber' : string,
  'roomType' : string,
}
export type ResidentId = Principal;
export type ResidentStatusUpdateResult = { 'activated' : null } |
  { 'terminated' : null } |
  { 'notFound' : null };
export interface ResidentUpdateRequest {
  'bed' : [] | [string],
  'birthDate' : string,
  'admissionDate' : string,
  'name' : string,
  'roomNumber' : string,
  'insurance' : InsuranceInfo,
  'medications' : Array<Medication>,
  'pharmacy' : PharmacyInfo,
  'responsiblePersons' : Array<ResponsiblePerson>,
  'medicaidNumber' : string,
  'physicians' : Array<Physician>,
  'roomType' : string,
  'medicareNumber' : string,
}
export type ResidentUpdateResult = { 'notFound' : null } |
  { 'updated' : null };
export interface ResidentsDirectoryResponse {
  'residents' : Array<ResidentDirectoryEntry>,
  'directoryLoadPerformance' : DirectoryLoadPerformance,
}
export interface ResponsiblePerson {
  'relationship' : string,
  'name' : string,
  'address' : string,
  'contactNumber' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VitalsRecord {
  'temperature' : number,
  'bloodPressure' : string,
  'timestamp' : bigint,
  'pulse' : bigint,
  'bloodOxygen' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAdlRecord' : ActorMethod<[ResidentId, AdlRecord], undefined>,
  'createMarRecord' : ActorMethod<[ResidentId, MarRecord], undefined>,
  'createResident' : ActorMethod<[ResidentCreateRequest], Resident>,
  'createVitalsEntry' : ActorMethod<[ResidentId, VitalsRecord], undefined>,
  'deleteAdlRecord' : ActorMethod<[ResidentId, bigint], undefined>,
  'deleteMarRecord' : ActorMethod<[ResidentId, bigint], undefined>,
  'deleteResident' : ActorMethod<[ResidentId], undefined>,
  'deleteVitalsEntry' : ActorMethod<[ResidentId, bigint], undefined>,
  'ensureResidentsSeeded' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getResident' : ActorMethod<[ResidentId], [] | [Resident]>,
  /**
   * / Residents Directory - Lightweight Endpoint for Residents Card Grid (Dashboard)
   */
  'getResidentsDirectory' : ActorMethod<[], ResidentsDirectoryResponse>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], HealthCheckResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isResidentActive' : ActorMethod<[ResidentId], boolean>,
  'listActiveResidents' : ActorMethod<[], Array<Resident>>,
  'listAdlRecords' : ActorMethod<[ResidentId], Array<AdlRecord>>,
  'listMarRecords' : ActorMethod<[ResidentId], Array<MarRecord>>,
  'listVitalsEntries' : ActorMethod<[ResidentId], Array<VitalsRecord>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleResidentStatus' : ActorMethod<
    [ResidentId],
    ResidentStatusUpdateResult
  >,
  'updateResident' : ActorMethod<
    [ResidentId, ResidentUpdateRequest],
    ResidentUpdateResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];