/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ResidentId = IDL.Principal;
export const AdlRecord = IDL.Record({
  'activityType' : IDL.Text,
  'assistanceLevel' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'supervisorId' : IDL.Principal,
});
export const MarRecord = IDL.Record({
  'medicationName' : IDL.Text,
  'dosage' : IDL.Text,
  'nurseId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'administrationTime' : IDL.Text,
});
export const ResidentCreateRequest = IDL.Record({
  'id' : ResidentId,
  'birthDate' : IDL.Text,
  'name' : IDL.Text,
});
export const Resident = IDL.Record({
  'id' : ResidentId,
  'active' : IDL.Bool,
  'birthDate' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const VitalsRecord = IDL.Record({
  'temperature' : IDL.Float64,
  'bloodPressure' : IDL.Text,
  'timestamp' : IDL.Int,
  'pulse' : IDL.Nat,
  'bloodOxygen' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ResidentStatusUpdateResult = IDL.Variant({
  'activated' : IDL.Null,
  'terminated' : IDL.Null,
  'notFound' : IDL.Null,
});
export const ResidentUpdateRequest = IDL.Record({
  'birthDate' : IDL.Text,
  'name' : IDL.Text,
});
export const ResidentUpdateResult = IDL.Variant({
  'notFound' : IDL.Null,
  'updated' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdlRecord' : IDL.Func([ResidentId, AdlRecord], [], []),
  'createMarRecord' : IDL.Func([ResidentId, MarRecord], [], []),
  'createResident' : IDL.Func([ResidentCreateRequest], [Resident], []),
  'createVitalsEntry' : IDL.Func([ResidentId, VitalsRecord], [], []),
  'deleteAdlRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
  'deleteMarRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
  'deleteResident' : IDL.Func([ResidentId], [], []),
  'deleteVitalsEntry' : IDL.Func([ResidentId, IDL.Int], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getResident' : IDL.Func([ResidentId], [IDL.Opt(Resident)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isResidentActive' : IDL.Func([ResidentId], [IDL.Bool], []),
  'listActiveResidents' : IDL.Func([], [IDL.Vec(Resident)], ['query']),
  'listAdlRecords' : IDL.Func([ResidentId], [IDL.Vec(AdlRecord)], ['query']),
  'listMarRecords' : IDL.Func([ResidentId], [IDL.Vec(MarRecord)], ['query']),
  'listVitalsEntries' : IDL.Func(
      [ResidentId],
      [IDL.Vec(VitalsRecord)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleResidentStatus' : IDL.Func(
      [ResidentId],
      [ResidentStatusUpdateResult],
      [],
    ),
  'updateResident' : IDL.Func(
      [ResidentId, ResidentUpdateRequest],
      [ResidentUpdateResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ResidentId = IDL.Principal;
  const AdlRecord = IDL.Record({
    'activityType' : IDL.Text,
    'assistanceLevel' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'supervisorId' : IDL.Principal,
  });
  const MarRecord = IDL.Record({
    'medicationName' : IDL.Text,
    'dosage' : IDL.Text,
    'nurseId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'administrationTime' : IDL.Text,
  });
  const ResidentCreateRequest = IDL.Record({
    'id' : ResidentId,
    'birthDate' : IDL.Text,
    'name' : IDL.Text,
  });
  const Resident = IDL.Record({
    'id' : ResidentId,
    'active' : IDL.Bool,
    'birthDate' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const VitalsRecord = IDL.Record({
    'temperature' : IDL.Float64,
    'bloodPressure' : IDL.Text,
    'timestamp' : IDL.Int,
    'pulse' : IDL.Nat,
    'bloodOxygen' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ResidentStatusUpdateResult = IDL.Variant({
    'activated' : IDL.Null,
    'terminated' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const ResidentUpdateRequest = IDL.Record({
    'birthDate' : IDL.Text,
    'name' : IDL.Text,
  });
  const ResidentUpdateResult = IDL.Variant({
    'notFound' : IDL.Null,
    'updated' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdlRecord' : IDL.Func([ResidentId, AdlRecord], [], []),
    'createMarRecord' : IDL.Func([ResidentId, MarRecord], [], []),
    'createResident' : IDL.Func([ResidentCreateRequest], [Resident], []),
    'createVitalsEntry' : IDL.Func([ResidentId, VitalsRecord], [], []),
    'deleteAdlRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
    'deleteMarRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
    'deleteResident' : IDL.Func([ResidentId], [], []),
    'deleteVitalsEntry' : IDL.Func([ResidentId, IDL.Int], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getResident' : IDL.Func([ResidentId], [IDL.Opt(Resident)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isResidentActive' : IDL.Func([ResidentId], [IDL.Bool], []),
    'listActiveResidents' : IDL.Func([], [IDL.Vec(Resident)], ['query']),
    'listAdlRecords' : IDL.Func([ResidentId], [IDL.Vec(AdlRecord)], ['query']),
    'listMarRecords' : IDL.Func([ResidentId], [IDL.Vec(MarRecord)], ['query']),
    'listVitalsEntries' : IDL.Func(
        [ResidentId],
        [IDL.Vec(VitalsRecord)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleResidentStatus' : IDL.Func(
        [ResidentId],
        [ResidentStatusUpdateResult],
        [],
      ),
    'updateResident' : IDL.Func(
        [ResidentId, ResidentUpdateRequest],
        [ResidentUpdateResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };