/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResidentId = IDL.Principal;
export const MedicationStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'active' : IDL.Null,
  'discontinued' : IDL.Null,
});
export const MedicationRoute = IDL.Variant({
  'injection' : IDL.Null,
  'other' : IDL.Text,
  'subcutaneous_SubQ' : IDL.Null,
  'oral' : IDL.Null,
  'otic' : IDL.Null,
  'ophthalmic' : IDL.Null,
  'vaginal' : IDL.Null,
  'intravenous_IV' : IDL.Null,
  'sublingual_SL' : IDL.Null,
  'nasal' : IDL.Null,
  'transdermal' : IDL.Null,
  'inhalation' : IDL.Null,
  'intramuscular_IM' : IDL.Null,
  'topical' : IDL.Null,
  'rectal' : IDL.Null,
});
export const Medication = IDL.Record({
  'id' : IDL.Nat,
  'status' : MedicationStatus,
  'medicationName' : IDL.Text,
  'dosage' : IDL.Text,
  'prescribingPhysician' : IDL.Text,
  'administrationTimes' : IDL.Vec(IDL.Text),
  'route' : IDL.Opt(MedicationRoute),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdlRecord = IDL.Record({
  'activityType' : IDL.Text,
  'assistanceLevel' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'supervisorId' : IDL.Principal,
});
export const MarRecord = IDL.Record({
  'medicationName' : IDL.Text,
  'dosage' : IDL.Text,
  'nurseId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'administrationTime' : IDL.Text,
});
export const InsuranceInfo = IDL.Record({
  'company' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
  'policyNumber' : IDL.Text,
});
export const PharmacyInfo = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const ResponsiblePerson = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const Physician = IDL.Record({
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const ResidentCreateRequest = IDL.Record({
  'id' : ResidentId,
  'bed' : IDL.Opt(IDL.Text),
  'birthDate' : IDL.Text,
  'admissionDate' : IDL.Text,
  'name' : IDL.Text,
  'roomNumber' : IDL.Text,
  'insurance' : InsuranceInfo,
  'medications' : IDL.Vec(Medication),
  'pharmacy' : PharmacyInfo,
  'responsiblePersons' : IDL.Vec(ResponsiblePerson),
  'medicaidNumber' : IDL.Text,
  'physicians' : IDL.Vec(Physician),
  'roomType' : IDL.Text,
  'medicareNumber' : IDL.Text,
});
export const Resident = IDL.Record({
  'id' : ResidentId,
  'bed' : IDL.Opt(IDL.Text),
  'active' : IDL.Bool,
  'birthDate' : IDL.Text,
  'owner' : IDL.Principal,
  'admissionDate' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'roomNumber' : IDL.Text,
  'insurance' : InsuranceInfo,
  'medications' : IDL.Vec(Medication),
  'pharmacy' : PharmacyInfo,
  'responsiblePersons' : IDL.Vec(ResponsiblePerson),
  'medicaidNumber' : IDL.Text,
  'physicians' : IDL.Vec(Physician),
  'roomType' : IDL.Text,
  'medicareNumber' : IDL.Text,
});
export const VitalsRecord = IDL.Record({
  'temperature' : IDL.Float64,
  'bloodPressure' : IDL.Text,
  'timestamp' : IDL.Int,
  'pulse' : IDL.Nat,
  'bloodOxygen' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ResidentDirectoryEntry = IDL.Record({
  'id' : ResidentId,
  'bed' : IDL.Opt(IDL.Text),
  'active' : IDL.Bool,
  'birthDate' : IDL.Text,
  'admissionDate' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'roomNumber' : IDL.Text,
  'roomType' : IDL.Text,
});
export const DirectoryLoadPerformance = IDL.Record({
  'backendQueryTimeNanos' : IDL.Nat64,
  'totalRequestTimeNanos' : IDL.Nat64,
  'residentCount' : IDL.Nat,
});
export const ResidentsDirectoryResponse = IDL.Record({
  'residents' : IDL.Vec(ResidentDirectoryEntry),
  'directoryLoadPerformance' : DirectoryLoadPerformance,
});
export const HealthCheckResponse = IDL.Record({
  'status' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'canisterId' : IDL.Text,
});
export const ResidentStatusUpdateResult = IDL.Variant({
  'activated' : IDL.Null,
  'terminated' : IDL.Null,
  'notFound' : IDL.Null,
});
export const MedicationUpdate = IDL.Record({
  'id' : IDL.Nat,
  'status' : MedicationStatus,
  'medicationName' : IDL.Text,
  'dosage' : IDL.Text,
  'prescribingPhysician' : IDL.Text,
  'administrationTimes' : IDL.Vec(IDL.Text),
  'route' : IDL.Opt(MedicationRoute),
});
export const ResidentUpdateRequest = IDL.Record({
  'bed' : IDL.Opt(IDL.Text),
  'birthDate' : IDL.Text,
  'admissionDate' : IDL.Text,
  'name' : IDL.Text,
  'roomNumber' : IDL.Text,
  'insurance' : InsuranceInfo,
  'medications' : IDL.Vec(Medication),
  'pharmacy' : PharmacyInfo,
  'responsiblePersons' : IDL.Vec(ResponsiblePerson),
  'medicaidNumber' : IDL.Text,
  'physicians' : IDL.Vec(Physician),
  'roomType' : IDL.Text,
  'medicareNumber' : IDL.Text,
});
export const ResidentUpdateResult = IDL.Variant({
  'notFound' : IDL.Null,
  'updated' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedication' : IDL.Func([ResidentId, Medication], [Medication], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdlRecord' : IDL.Func([ResidentId, AdlRecord], [], []),
  'createMarRecord' : IDL.Func([ResidentId, MarRecord], [], []),
  'createResident' : IDL.Func([ResidentCreateRequest], [Resident], []),
  'createVitalsEntry' : IDL.Func([ResidentId, VitalsRecord], [], []),
  'deleteAdlRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
  'deleteMarRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
  'deleteMedication' : IDL.Func([ResidentId, IDL.Nat], [], []),
  'deleteResident' : IDL.Func([ResidentId], [], []),
  'deleteVitalsEntry' : IDL.Func([ResidentId, IDL.Int], [], []),
  'discontinueMedication' : IDL.Func([ResidentId, IDL.Nat], [Medication], []),
  'ensureResidentsSeeded' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getResident' : IDL.Func([ResidentId], [IDL.Opt(Resident)], ['query']),
  'getResidentsDirectory' : IDL.Func(
      [],
      [ResidentsDirectoryResponse],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'healthCheck' : IDL.Func([], [HealthCheckResponse], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isResidentActive' : IDL.Func([ResidentId], [IDL.Bool], ['query']),
  'listActiveResidents' : IDL.Func([], [IDL.Vec(Resident)], ['query']),
  'listAdlRecords' : IDL.Func([ResidentId], [IDL.Vec(AdlRecord)], ['query']),
  'listMarRecords' : IDL.Func([ResidentId], [IDL.Vec(MarRecord)], ['query']),
  'listVitalsEntries' : IDL.Func(
      [ResidentId],
      [IDL.Vec(VitalsRecord)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleResidentStatus' : IDL.Func(
      [ResidentId],
      [ResidentStatusUpdateResult],
      [],
    ),
  'updateMedication' : IDL.Func(
      [ResidentId, MedicationUpdate],
      [Medication],
      [],
    ),
  'updateResident' : IDL.Func(
      [ResidentId, ResidentUpdateRequest],
      [ResidentUpdateResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResidentId = IDL.Principal;
  const MedicationStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'active' : IDL.Null,
    'discontinued' : IDL.Null,
  });
  const MedicationRoute = IDL.Variant({
    'injection' : IDL.Null,
    'other' : IDL.Text,
    'subcutaneous_SubQ' : IDL.Null,
    'oral' : IDL.Null,
    'otic' : IDL.Null,
    'ophthalmic' : IDL.Null,
    'vaginal' : IDL.Null,
    'intravenous_IV' : IDL.Null,
    'sublingual_SL' : IDL.Null,
    'nasal' : IDL.Null,
    'transdermal' : IDL.Null,
    'inhalation' : IDL.Null,
    'intramuscular_IM' : IDL.Null,
    'topical' : IDL.Null,
    'rectal' : IDL.Null,
  });
  const Medication = IDL.Record({
    'id' : IDL.Nat,
    'status' : MedicationStatus,
    'medicationName' : IDL.Text,
    'dosage' : IDL.Text,
    'prescribingPhysician' : IDL.Text,
    'administrationTimes' : IDL.Vec(IDL.Text),
    'route' : IDL.Opt(MedicationRoute),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdlRecord = IDL.Record({
    'activityType' : IDL.Text,
    'assistanceLevel' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'supervisorId' : IDL.Principal,
  });
  const MarRecord = IDL.Record({
    'medicationName' : IDL.Text,
    'dosage' : IDL.Text,
    'nurseId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'administrationTime' : IDL.Text,
  });
  const InsuranceInfo = IDL.Record({
    'company' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
    'policyNumber' : IDL.Text,
  });
  const PharmacyInfo = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const ResponsiblePerson = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const Physician = IDL.Record({
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const ResidentCreateRequest = IDL.Record({
    'id' : ResidentId,
    'bed' : IDL.Opt(IDL.Text),
    'birthDate' : IDL.Text,
    'admissionDate' : IDL.Text,
    'name' : IDL.Text,
    'roomNumber' : IDL.Text,
    'insurance' : InsuranceInfo,
    'medications' : IDL.Vec(Medication),
    'pharmacy' : PharmacyInfo,
    'responsiblePersons' : IDL.Vec(ResponsiblePerson),
    'medicaidNumber' : IDL.Text,
    'physicians' : IDL.Vec(Physician),
    'roomType' : IDL.Text,
    'medicareNumber' : IDL.Text,
  });
  const Resident = IDL.Record({
    'id' : ResidentId,
    'bed' : IDL.Opt(IDL.Text),
    'active' : IDL.Bool,
    'birthDate' : IDL.Text,
    'owner' : IDL.Principal,
    'admissionDate' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'roomNumber' : IDL.Text,
    'insurance' : InsuranceInfo,
    'medications' : IDL.Vec(Medication),
    'pharmacy' : PharmacyInfo,
    'responsiblePersons' : IDL.Vec(ResponsiblePerson),
    'medicaidNumber' : IDL.Text,
    'physicians' : IDL.Vec(Physician),
    'roomType' : IDL.Text,
    'medicareNumber' : IDL.Text,
  });
  const VitalsRecord = IDL.Record({
    'temperature' : IDL.Float64,
    'bloodPressure' : IDL.Text,
    'timestamp' : IDL.Int,
    'pulse' : IDL.Nat,
    'bloodOxygen' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ResidentDirectoryEntry = IDL.Record({
    'id' : ResidentId,
    'bed' : IDL.Opt(IDL.Text),
    'active' : IDL.Bool,
    'birthDate' : IDL.Text,
    'admissionDate' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'roomNumber' : IDL.Text,
    'roomType' : IDL.Text,
  });
  const DirectoryLoadPerformance = IDL.Record({
    'backendQueryTimeNanos' : IDL.Nat64,
    'totalRequestTimeNanos' : IDL.Nat64,
    'residentCount' : IDL.Nat,
  });
  const ResidentsDirectoryResponse = IDL.Record({
    'residents' : IDL.Vec(ResidentDirectoryEntry),
    'directoryLoadPerformance' : DirectoryLoadPerformance,
  });
  const HealthCheckResponse = IDL.Record({
    'status' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'canisterId' : IDL.Text,
  });
  const ResidentStatusUpdateResult = IDL.Variant({
    'activated' : IDL.Null,
    'terminated' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const MedicationUpdate = IDL.Record({
    'id' : IDL.Nat,
    'status' : MedicationStatus,
    'medicationName' : IDL.Text,
    'dosage' : IDL.Text,
    'prescribingPhysician' : IDL.Text,
    'administrationTimes' : IDL.Vec(IDL.Text),
    'route' : IDL.Opt(MedicationRoute),
  });
  const ResidentUpdateRequest = IDL.Record({
    'bed' : IDL.Opt(IDL.Text),
    'birthDate' : IDL.Text,
    'admissionDate' : IDL.Text,
    'name' : IDL.Text,
    'roomNumber' : IDL.Text,
    'insurance' : InsuranceInfo,
    'medications' : IDL.Vec(Medication),
    'pharmacy' : PharmacyInfo,
    'responsiblePersons' : IDL.Vec(ResponsiblePerson),
    'medicaidNumber' : IDL.Text,
    'physicians' : IDL.Vec(Physician),
    'roomType' : IDL.Text,
    'medicareNumber' : IDL.Text,
  });
  const ResidentUpdateResult = IDL.Variant({
    'notFound' : IDL.Null,
    'updated' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedication' : IDL.Func([ResidentId, Medication], [Medication], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdlRecord' : IDL.Func([ResidentId, AdlRecord], [], []),
    'createMarRecord' : IDL.Func([ResidentId, MarRecord], [], []),
    'createResident' : IDL.Func([ResidentCreateRequest], [Resident], []),
    'createVitalsEntry' : IDL.Func([ResidentId, VitalsRecord], [], []),
    'deleteAdlRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
    'deleteMarRecord' : IDL.Func([ResidentId, IDL.Int], [], []),
    'deleteMedication' : IDL.Func([ResidentId, IDL.Nat], [], []),
    'deleteResident' : IDL.Func([ResidentId], [], []),
    'deleteVitalsEntry' : IDL.Func([ResidentId, IDL.Int], [], []),
    'discontinueMedication' : IDL.Func([ResidentId, IDL.Nat], [Medication], []),
    'ensureResidentsSeeded' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getResident' : IDL.Func([ResidentId], [IDL.Opt(Resident)], ['query']),
    'getResidentsDirectory' : IDL.Func(
        [],
        [ResidentsDirectoryResponse],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'healthCheck' : IDL.Func([], [HealthCheckResponse], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isResidentActive' : IDL.Func([ResidentId], [IDL.Bool], ['query']),
    'listActiveResidents' : IDL.Func([], [IDL.Vec(Resident)], ['query']),
    'listAdlRecords' : IDL.Func([ResidentId], [IDL.Vec(AdlRecord)], ['query']),
    'listMarRecords' : IDL.Func([ResidentId], [IDL.Vec(MarRecord)], ['query']),
    'listVitalsEntries' : IDL.Func(
        [ResidentId],
        [IDL.Vec(VitalsRecord)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleResidentStatus' : IDL.Func(
        [ResidentId],
        [ResidentStatusUpdateResult],
        [],
      ),
    'updateMedication' : IDL.Func(
        [ResidentId, MedicationUpdate],
        [Medication],
        [],
      ),
    'updateResident' : IDL.Func(
        [ResidentId, ResidentUpdateRequest],
        [ResidentUpdateResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };