/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InsuranceInfo {
    company: string;
    address: string;
    contactNumber: string;
    policyNumber: string;
}
export interface ResidentUpdateRequest {
    bed?: string;
    birthDate: string;
    admissionDate: string;
    name: string;
    roomNumber: string;
    insurance: InsuranceInfo;
    medications: Array<Medication>;
    pharmacy: PharmacyInfo;
    responsiblePersons: Array<ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<Physician>;
    roomType: string;
    medicareNumber: string;
}
export interface PharmacyInfo {
    name: string;
    address: string;
    contactNumber: string;
}
export interface MarRecord {
    medicationName: string;
    dosage: string;
    nurseId: Principal;
    timestamp: bigint;
    administrationTime: string;
}
export interface Resident {
    id: ResidentId;
    bed?: string;
    active: boolean;
    birthDate: string;
    owner: Principal;
    admissionDate: string;
    name: string;
    createdAt: bigint;
    roomNumber: string;
    insurance: InsuranceInfo;
    medications: Array<Medication>;
    pharmacy: PharmacyInfo;
    responsiblePersons: Array<ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<Physician>;
    roomType: string;
    medicareNumber: string;
}
export interface Physician {
    name: string;
    specialty: string;
    contactNumber: string;
}
export interface ResponsiblePerson {
    relationship: string;
    name: string;
    address: string;
    contactNumber: string;
}
export interface HealthCheckResponse {
    status: string;
    message: string;
    timestamp: bigint;
    canisterId: string;
}
export interface ResidentCreateRequest {
    id: ResidentId;
    bed?: string;
    birthDate: string;
    admissionDate: string;
    name: string;
    roomNumber: string;
    insurance: InsuranceInfo;
    medications: Array<Medication>;
    pharmacy: PharmacyInfo;
    responsiblePersons: Array<ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<Physician>;
    roomType: string;
    medicareNumber: string;
}
export interface AdlRecord {
    activityType: string;
    assistanceLevel: string;
    notes: string;
    timestamp: bigint;
    supervisorId: Principal;
}
export interface ResidentsDirectoryResponse {
    residents: Array<ResidentDirectoryEntry>;
    directoryLoadPerformance: DirectoryLoadPerformance;
}
export interface VitalsRecord {
    temperature: number;
    bloodPressure: string;
    timestamp: bigint;
    pulse: bigint;
    bloodOxygen: bigint;
}
export type ResidentId = Principal;
export interface ResidentDirectoryEntry {
    id: ResidentId;
    bed?: string;
    active: boolean;
    birthDate: string;
    admissionDate: string;
    name: string;
    createdAt: bigint;
    roomNumber: string;
    roomType: string;
}
export interface DirectoryLoadPerformance {
    backendQueryTimeNanos: bigint;
    totalRequestTimeNanos: bigint;
    residentCount: bigint;
}
export interface UserProfile {
    name: string;
}
export interface Medication {
    medicationName: string;
    dosage: string;
    prescribingPhysician: string;
    administrationTimes: Array<string>;
}
export enum ResidentStatusUpdateResult {
    activated = "activated",
    terminated = "terminated",
    notFound = "notFound"
}
export enum ResidentUpdateResult {
    notFound = "notFound",
    updated = "updated"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAdlRecord(residentId: ResidentId, record: AdlRecord): Promise<void>;
    createMarRecord(residentId: ResidentId, record: MarRecord): Promise<void>;
    createResident(request: ResidentCreateRequest): Promise<Resident>;
    createVitalsEntry(residentId: ResidentId, record: VitalsRecord): Promise<void>;
    deleteAdlRecord(residentId: ResidentId, timestamp: bigint): Promise<void>;
    deleteMarRecord(residentId: ResidentId, timestamp: bigint): Promise<void>;
    deleteResident(id: ResidentId): Promise<void>;
    deleteVitalsEntry(residentId: ResidentId, timestamp: bigint): Promise<void>;
    ensureResidentsSeeded(): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getResident(id: ResidentId): Promise<Resident | null>;
    /**
     * / Residents Directory - Lightweight Endpoint for Residents Card Grid (Dashboard)
     */
    getResidentsDirectory(): Promise<ResidentsDirectoryResponse>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    healthCheck(): Promise<HealthCheckResponse>;
    isCallerAdmin(): Promise<boolean>;
    isResidentActive(residentId: ResidentId): Promise<boolean>;
    listActiveResidents(): Promise<Array<Resident>>;
    listAdlRecords(residentId: ResidentId): Promise<Array<AdlRecord>>;
    listMarRecords(residentId: ResidentId): Promise<Array<MarRecord>>;
    listVitalsEntries(residentId: ResidentId): Promise<Array<VitalsRecord>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleResidentStatus(id: ResidentId): Promise<ResidentStatusUpdateResult>;
    updateResident(id: ResidentId, updateRequest: ResidentUpdateRequest): Promise<ResidentUpdateResult>;
}
import type { DirectoryLoadPerformance as _DirectoryLoadPerformance, InsuranceInfo as _InsuranceInfo, Medication as _Medication, PharmacyInfo as _PharmacyInfo, Physician as _Physician, Resident as _Resident, ResidentCreateRequest as _ResidentCreateRequest, ResidentDirectoryEntry as _ResidentDirectoryEntry, ResidentId as _ResidentId, ResidentStatusUpdateResult as _ResidentStatusUpdateResult, ResidentUpdateRequest as _ResidentUpdateRequest, ResidentUpdateResult as _ResidentUpdateResult, ResidentsDirectoryResponse as _ResidentsDirectoryResponse, ResponsiblePerson as _ResponsiblePerson, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAdlRecord(arg0: ResidentId, arg1: AdlRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdlRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdlRecord(arg0, arg1);
            return result;
        }
    }
    async createMarRecord(arg0: ResidentId, arg1: MarRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarRecord(arg0, arg1);
            return result;
        }
    }
    async createResident(arg0: ResidentCreateRequest): Promise<Resident> {
        if (this.processError) {
            try {
                const result = await this.actor.createResident(to_candid_ResidentCreateRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Resident_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResident(to_candid_ResidentCreateRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Resident_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createVitalsEntry(arg0: ResidentId, arg1: VitalsRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVitalsEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVitalsEntry(arg0, arg1);
            return result;
        }
    }
    async deleteAdlRecord(arg0: ResidentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdlRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdlRecord(arg0, arg1);
            return result;
        }
    }
    async deleteMarRecord(arg0: ResidentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMarRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMarRecord(arg0, arg1);
            return result;
        }
    }
    async deleteResident(arg0: ResidentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResident(arg0);
            return result;
        }
    }
    async deleteVitalsEntry(arg0: ResidentId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVitalsEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVitalsEntry(arg0, arg1);
            return result;
        }
    }
    async ensureResidentsSeeded(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureResidentsSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureResidentsSeeded();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResident(arg0: ResidentId): Promise<Resident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResident(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResident(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResidentsDirectory(): Promise<ResidentsDirectoryResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getResidentsDirectory();
                return from_candid_ResidentsDirectoryResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResidentsDirectory();
            return from_candid_ResidentsDirectoryResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async healthCheck(): Promise<HealthCheckResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.healthCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.healthCheck();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isResidentActive(arg0: ResidentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isResidentActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isResidentActive(arg0);
            return result;
        }
    }
    async listActiveResidents(): Promise<Array<Resident>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveResidents();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveResidents();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAdlRecords(arg0: ResidentId): Promise<Array<AdlRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdlRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdlRecords(arg0);
            return result;
        }
    }
    async listMarRecords(arg0: ResidentId): Promise<Array<MarRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMarRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMarRecords(arg0);
            return result;
        }
    }
    async listVitalsEntries(arg0: ResidentId): Promise<Array<VitalsRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVitalsEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVitalsEntries(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleResidentStatus(arg0: ResidentId): Promise<ResidentStatusUpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleResidentStatus(arg0);
                return from_candid_ResidentStatusUpdateResult_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleResidentStatus(arg0);
            return from_candid_ResidentStatusUpdateResult_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResident(arg0: ResidentId, arg1: ResidentUpdateRequest): Promise<ResidentUpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResident(arg0, to_candid_ResidentUpdateRequest_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ResidentUpdateResult_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResident(arg0, to_candid_ResidentUpdateRequest_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ResidentUpdateResult_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ResidentDirectoryEntry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResidentDirectoryEntry): ResidentDirectoryEntry {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ResidentStatusUpdateResult_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResidentStatusUpdateResult): ResidentStatusUpdateResult {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ResidentUpdateResult_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResidentUpdateResult): ResidentUpdateResult {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Resident_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resident): Resident {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ResidentsDirectoryResponse_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResidentsDirectoryResponse): ResidentsDirectoryResponse {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resident]): Resident | null {
    return value.length === 0 ? null : from_candid_Resident_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    residents: Array<_ResidentDirectoryEntry>;
    directoryLoadPerformance: _DirectoryLoadPerformance;
}): {
    residents: Array<ResidentDirectoryEntry>;
    directoryLoadPerformance: DirectoryLoadPerformance;
} {
    return {
        residents: from_candid_vec_n14(_uploadFile, _downloadFile, value.residents),
        directoryLoadPerformance: value.directoryLoadPerformance
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResidentId;
    bed: [] | [string];
    active: boolean;
    birthDate: string;
    admissionDate: string;
    name: string;
    createdAt: bigint;
    roomNumber: string;
    roomType: string;
}): {
    id: ResidentId;
    bed?: string;
    active: boolean;
    birthDate: string;
    admissionDate: string;
    name: string;
    createdAt: bigint;
    roomNumber: string;
    roomType: string;
} {
    return {
        id: value.id,
        bed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bed)),
        active: value.active,
        birthDate: value.birthDate,
        admissionDate: value.admissionDate,
        name: value.name,
        createdAt: value.createdAt,
        roomNumber: value.roomNumber,
        roomType: value.roomType
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResidentId;
    bed: [] | [string];
    active: boolean;
    birthDate: string;
    owner: Principal;
    admissionDate: string;
    name: string;
    createdAt: bigint;
    roomNumber: string;
    insurance: _InsuranceInfo;
    medications: Array<_Medication>;
    pharmacy: _PharmacyInfo;
    responsiblePersons: Array<_ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<_Physician>;
    roomType: string;
    medicareNumber: string;
}): {
    id: ResidentId;
    bed?: string;
    active: boolean;
    birthDate: string;
    owner: Principal;
    admissionDate: string;
    name: string;
    createdAt: bigint;
    roomNumber: string;
    insurance: InsuranceInfo;
    medications: Array<Medication>;
    pharmacy: PharmacyInfo;
    responsiblePersons: Array<ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<Physician>;
    roomType: string;
    medicareNumber: string;
} {
    return {
        id: value.id,
        bed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bed)),
        active: value.active,
        birthDate: value.birthDate,
        owner: value.owner,
        admissionDate: value.admissionDate,
        name: value.name,
        createdAt: value.createdAt,
        roomNumber: value.roomNumber,
        insurance: value.insurance,
        medications: value.medications,
        pharmacy: value.pharmacy,
        responsiblePersons: value.responsiblePersons,
        medicaidNumber: value.medicaidNumber,
        physicians: value.physicians,
        roomType: value.roomType,
        medicareNumber: value.medicareNumber
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activated: null;
} | {
    terminated: null;
} | {
    notFound: null;
}): ResidentStatusUpdateResult {
    return "activated" in value ? ResidentStatusUpdateResult.activated : "terminated" in value ? ResidentStatusUpdateResult.terminated : "notFound" in value ? ResidentStatusUpdateResult.notFound : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    updated: null;
}): ResidentUpdateResult {
    return "notFound" in value ? ResidentUpdateResult.notFound : "updated" in value ? ResidentUpdateResult.updated : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResidentDirectoryEntry>): Array<ResidentDirectoryEntry> {
    return value.map((x)=>from_candid_ResidentDirectoryEntry_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resident>): Array<Resident> {
    return value.map((x)=>from_candid_Resident_n5(_uploadFile, _downloadFile, x));
}
function to_candid_ResidentCreateRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentCreateRequest): _ResidentCreateRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ResidentUpdateRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResidentUpdateRequest): _ResidentUpdateRequest {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bed?: string;
    birthDate: string;
    admissionDate: string;
    name: string;
    roomNumber: string;
    insurance: InsuranceInfo;
    medications: Array<Medication>;
    pharmacy: PharmacyInfo;
    responsiblePersons: Array<ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<Physician>;
    roomType: string;
    medicareNumber: string;
}): {
    bed: [] | [string];
    birthDate: string;
    admissionDate: string;
    name: string;
    roomNumber: string;
    insurance: _InsuranceInfo;
    medications: Array<_Medication>;
    pharmacy: _PharmacyInfo;
    responsiblePersons: Array<_ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<_Physician>;
    roomType: string;
    medicareNumber: string;
} {
    return {
        bed: value.bed ? candid_some(value.bed) : candid_none(),
        birthDate: value.birthDate,
        admissionDate: value.admissionDate,
        name: value.name,
        roomNumber: value.roomNumber,
        insurance: value.insurance,
        medications: value.medications,
        pharmacy: value.pharmacy,
        responsiblePersons: value.responsiblePersons,
        medicaidNumber: value.medicaidNumber,
        physicians: value.physicians,
        roomType: value.roomType,
        medicareNumber: value.medicareNumber
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ResidentId;
    bed?: string;
    birthDate: string;
    admissionDate: string;
    name: string;
    roomNumber: string;
    insurance: InsuranceInfo;
    medications: Array<Medication>;
    pharmacy: PharmacyInfo;
    responsiblePersons: Array<ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<Physician>;
    roomType: string;
    medicareNumber: string;
}): {
    id: _ResidentId;
    bed: [] | [string];
    birthDate: string;
    admissionDate: string;
    name: string;
    roomNumber: string;
    insurance: _InsuranceInfo;
    medications: Array<_Medication>;
    pharmacy: _PharmacyInfo;
    responsiblePersons: Array<_ResponsiblePerson>;
    medicaidNumber: string;
    physicians: Array<_Physician>;
    roomType: string;
    medicareNumber: string;
} {
    return {
        id: value.id,
        bed: value.bed ? candid_some(value.bed) : candid_none(),
        birthDate: value.birthDate,
        admissionDate: value.admissionDate,
        name: value.name,
        roomNumber: value.roomNumber,
        insurance: value.insurance,
        medications: value.medications,
        pharmacy: value.pharmacy,
        responsiblePersons: value.responsiblePersons,
        medicaidNumber: value.medicaidNumber,
        physicians: value.physicians,
        roomType: value.roomType,
        medicareNumber: value.medicareNumber
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
